### ISSUE TITLE
Error: Your URL might be to a direct download

### ISSUE THREAD

**Issue by Inside4ndroid** [DmitryOvchinikov/APK-Installer#1]
I am constantly getting this error on android 10+ it seems to work fine on older versions???

Any fix???

**Comment by DmitryOvchinikov** [comment]
Hey, I have used AsyncTask for this library, and it was deprecated shortly after I completed it, so the library does not work on newer versions of android.
You are welcome to inspect the code I used and adapt it for your own needs!
Cheers.

**Comment by Inside4ndroid** [comment]
hi thanks for the reply....

i have edited and created a pull request :)

its only a quick (dirty) fix but it works :)
